/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bortoneespinoza_so2;

/**
 *
 * @author isabe
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        
        int i = 0;
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        //iniciar 20 hilos, 10 y 10. POR HACER 
        
        while (true) {          

            i++;

//            Node node = new Node();

            if (i==10) { break;}

        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloT = new javax.swing.JLabel();
        TituloS = new javax.swing.JLabel();
        streetImg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        medior_tiempo = new javax.swing.JSpinner();
        batallas_zelda = new javax.swing.JLabel();
        vs_imagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        zeldaImg = new javax.swing.JLabel();
        batallas_street = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        streetName = new javax.swing.JLabel();
        zeldaName = new javax.swing.JLabel();
        zeldaName1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TituloT.setForeground(new java.awt.Color(0, 102, 0));
        TituloT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TearsFondo (1)_1.png"))); // NOI18N
        jPanel1.add(TituloT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 180));

        TituloS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TituloS.setForeground(new java.awt.Color(0, 0, 204));
        TituloS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/StreetFondo (2).png"))); // NOI18N
        jPanel1.add(TituloS, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, 150));

        streetImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        streetImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/STREET_Fei_Long.jpg"))); // NOI18N
        jPanel1.add(streetImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 80, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/456-4568018_you-win-png-street-fighter-you-win-png-removebg-preview (3) (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 170, 520));

        medior_tiempo.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        medior_tiempo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.add(medior_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 40, 30));

        batallas_zelda.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        batallas_zelda.setForeground(new java.awt.Color(255, 255, 255));
        batallas_zelda.setText("Batallas Ganadas");
        jPanel1.add(batallas_zelda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 280, 60));

        vs_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png-transparent-vs-showdown-vs-calligraphy-pk-duel-game-vs-thumbnail-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(vs_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 170, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        zeldaImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zeldaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ZELDA_Link.jpg"))); // NOI18N
        jPanel1.add(zeldaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 80, 80));

        batallas_street.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        batallas_street.setForeground(new java.awt.Color(255, 255, 255));
        batallas_street.setText("Batallas Ganadas");
        jPanel1.add(batallas_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 270, 30));

        jLabel4.setText("Ganador");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, -1));

        streetName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        streetName.setForeground(new java.awt.Color(0, 0, 0));
        streetName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        streetName.setText("Nombre");
        jPanel1.add(streetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 90, -1));

        zeldaName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        zeldaName.setForeground(new java.awt.Color(0, 0, 0));
        zeldaName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zeldaName.setText("Nombre");
        jPanel1.add(zeldaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 90, -1));

        zeldaName1.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        zeldaName1.setForeground(new java.awt.Color(255, 255, 255));
        zeldaName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zeldaName1.setText("Estado");
        jPanel1.add(zeldaName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 170, -1));

        Fondo.setForeground(new java.awt.Color(0, 0, 102));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/812075.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 750, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel TituloS;
    private javax.swing.JLabel TituloT;
    private javax.swing.JLabel batallas_street;
    private javax.swing.JLabel batallas_zelda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner medior_tiempo;
    public static javax.swing.JLabel streetImg;
    public static javax.swing.JLabel streetName;
    private javax.swing.JLabel vs_imagen;
    public static javax.swing.JLabel zeldaImg;
    public static javax.swing.JLabel zeldaName;
    public static javax.swing.JLabel zeldaName1;
    // End of variables declaration//GEN-END:variables
}
