/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bortoneespinoza_so2;

import static bortoneespinoza_so2.Administrador.colaStreetFighterNivel1;
import static bortoneespinoza_so2.Administrador.colaStreetFighterNivel2;
import static bortoneespinoza_so2.Administrador.colaStreetFighterNivel3;
import static bortoneespinoza_so2.Administrador.colaStreetFighterNivel4;
import static bortoneespinoza_so2.Administrador.colaZeldaNivel1;
import static bortoneespinoza_so2.Administrador.colaZeldaNivel2;
import static bortoneespinoza_so2.Administrador.colaZeldaNivel3;
import static bortoneespinoza_so2.Administrador.colaZeldaNivel4;
import static bortoneespinoza_so2.InteligenciaArtificial.ganadores;
import static bortoneespinoza_so2.InteligenciaArtificial.cont_zelda;
import static bortoneespinoza_so2.InteligenciaArtificial.cont_street;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author isabe
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    public static int tiempo;
    
    public Interfaz() {

        
        int i = 0;

        initComponents();
        this.setLocationRelativeTo(null);
        
        //int tiempo = (int) medidor_tiempo.getValue();
        //System.out.println("TIEMPO: " + tiempo);

        //iniciar 20 hilos, 10 y 10. POR HACER 
        while (true) {

            i++;

//            Node node = new Node();
            if (i == 10) {
                break;
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPane5 = new java.awt.ScrollPane();
        cola3_zelda = new javax.swing.JLabel();
        scrollPane7 = new java.awt.ScrollPane();
        cola3_street = new javax.swing.JLabel();
        scrollPane6 = new java.awt.ScrollPane();
        cola2_street = new javax.swing.JLabel();
        scrollPane8 = new java.awt.ScrollPane();
        cola4_street = new javax.swing.JLabel();
        scrollPane2 = new java.awt.ScrollPane();
        cola4_zelda = new javax.swing.JLabel();
        scrollPane4 = new java.awt.ScrollPane();
        cola2_zelda = new javax.swing.JLabel();
        scrollPane3 = new java.awt.ScrollPane();
        cola1_street = new javax.swing.JLabel();
        empate = new javax.swing.JLabel();
        TituloS = new javax.swing.JLabel();
        trofeo_zelda = new javax.swing.JLabel();
        trofeo_street = new javax.swing.JLabel();
        streetImg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        medidor_tiempo = new javax.swing.JSpinner();
        batallas_zelda = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        cola1_zelda = new javax.swing.JLabel();
        vs_imagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        zeldaImg = new javax.swing.JLabel();
        batallas_street = new javax.swing.JLabel();
        scrollPane9 = new java.awt.ScrollPane();
        cola_ganadores = new javax.swing.JLabel();
        streetName = new javax.swing.JLabel();
        estadoBatalla = new javax.swing.JLabel();
        zeldaName = new javax.swing.JLabel();
        cont_zelda_label = new javax.swing.JLabel();
        cont_street_label = new javax.swing.JLabel();
        TituloS1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane5.setForeground(new java.awt.Color(0, 0, 0));

        cola3_zelda.setBackground(new java.awt.Color(255, 255, 255));
        cola3_zelda.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cola3_zelda.setText("Cola 3");
        scrollPane5.add(cola3_zelda);

        jPanel1.add(scrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 210, 30));

        scrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane7.setForeground(new java.awt.Color(0, 0, 0));

        cola3_street.setBackground(new java.awt.Color(255, 255, 255));
        cola3_street.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cola3_street.setText("Cola 3");
        scrollPane7.add(cola3_street);

        jPanel1.add(scrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 200, 30));

        scrollPane6.setBackground(new java.awt.Color(255, 255, 255));

        cola2_street.setBackground(new java.awt.Color(255, 255, 255));
        cola2_street.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cola2_street.setText("Cola 2");
        scrollPane6.add(cola2_street);

        jPanel1.add(scrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 200, 30));

        scrollPane8.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane8.setForeground(new java.awt.Color(0, 0, 0));

        cola4_street.setBackground(new java.awt.Color(255, 255, 255));
        cola4_street.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cola4_street.setText("Cola refuerzo");
        scrollPane8.add(cola4_street);

        jPanel1.add(scrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 200, 30));

        scrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane2.setForeground(new java.awt.Color(0, 0, 0));

        cola4_zelda.setBackground(new java.awt.Color(255, 255, 255));
        cola4_zelda.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cola4_zelda.setText("Cola refuerzo");
        scrollPane2.add(cola4_zelda);

        jPanel1.add(scrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 210, 30));

        scrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane4.setForeground(new java.awt.Color(0, 0, 0));

        cola2_zelda.setBackground(new java.awt.Color(255, 255, 255));
        cola2_zelda.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cola2_zelda.setText("Cola 2");
        scrollPane4.add(cola2_zelda);

        jPanel1.add(scrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, 30));

        scrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane3.setForeground(new java.awt.Color(0, 0, 0));

        cola1_street.setBackground(new java.awt.Color(255, 255, 255));
        cola1_street.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cola1_street.setText("Cola 1");
        scrollPane3.add(cola1_street);

        jPanel1.add(scrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 200, 30));

        empate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empate.png"))); // NOI18N
        jPanel1.add(empate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 210, 80));

        TituloS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TituloS.setForeground(new java.awt.Color(0, 0, 204));
        TituloS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TearsFondo (1)_1.png"))); // NOI18N
        jPanel1.add(TituloS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 160));

        trofeo_zelda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Screen-Shot-2016-12-03-at-7.59.54-PM-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(trofeo_zelda, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 80, 60));

        trofeo_street.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Screen-Shot-2016-12-03-at-7.59.54-PM-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(trofeo_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        streetImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        streetImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fei Long.jpg"))); // NOI18N
        jPanel1.add(streetImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 80, 80));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/456-4568018_you-win-png-street-fighter-you-win-png-removebg-preview (3) (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 130, 50));

        medidor_tiempo.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        medidor_tiempo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.add(medidor_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 40, 30));

        batallas_zelda.setFont(new java.awt.Font("Manjari Thin", 1, 18)); // NOI18N
        batallas_zelda.setForeground(new java.awt.Color(255, 255, 255));
        batallas_zelda.setText("Batallas Ganadas");
        jPanel1.add(batallas_zelda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 160, 60));

        cola1_zelda.setBackground(new java.awt.Color(255, 255, 255));
        cola1_zelda.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cola1_zelda.setText("Cola 1");
        cola1_zelda.setAutoscrolls(true);
        cola1_zelda.setOpaque(true);
        scrollPane1.add(cola1_zelda);

        jPanel1.add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 30));

        vs_imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png-transparent-vs-showdown-vs-calligraphy-pk-duel-game-vs-thumbnail-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(vs_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 90, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        zeldaImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zeldaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Link.jpg"))); // NOI18N
        jPanel1.add(zeldaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 80, 80));

        batallas_street.setFont(new java.awt.Font("Manjari Thin", 1, 18)); // NOI18N
        batallas_street.setForeground(new java.awt.Color(255, 255, 255));
        batallas_street.setText("Batallas Ganadas");
        jPanel1.add(batallas_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 160, 30));

        cola_ganadores.setBackground(new java.awt.Color(255, 255, 255));
        cola_ganadores.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cola_ganadores.setText("ganadores");
        cola_ganadores.setAutoscrolls(true);
        cola_ganadores.setOpaque(true);
        scrollPane9.add(cola_ganadores);

        jPanel1.add(scrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 210, 30));

        streetName.setFont(new java.awt.Font("Manjari Thin", 1, 18)); // NOI18N
        streetName.setForeground(new java.awt.Color(255, 255, 255));
        streetName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        streetName.setText("Nombre");
        jPanel1.add(streetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 90, -1));

        estadoBatalla.setFont(new java.awt.Font("Manjari Thin", 1, 24)); // NOI18N
        estadoBatalla.setForeground(new java.awt.Color(255, 255, 255));
        estadoBatalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoBatalla.setText("Estado");
        jPanel1.add(estadoBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 170, -1));

        zeldaName.setFont(new java.awt.Font("Manjari Thin", 1, 18)); // NOI18N
        zeldaName.setForeground(new java.awt.Color(255, 255, 255));
        zeldaName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zeldaName.setText("Nombre");
        jPanel1.add(zeldaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 180, 20));

        cont_zelda_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cont_zelda_label.setForeground(new java.awt.Color(255, 255, 255));
        cont_zelda_label.setText("X");
        jPanel1.add(cont_zelda_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 40, 20));

        cont_street_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cont_street_label.setForeground(new java.awt.Color(255, 255, 255));
        cont_street_label.setText("Y");
        jPanel1.add(cont_street_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 40, 40));

        TituloS1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TituloS1.setForeground(new java.awt.Color(0, 0, 204));
        TituloS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/StreetFondo (2).png"))); // NOI18N
        jPanel1.add(TituloS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, 150));

        Fondo.setForeground(new java.awt.Color(0, 0, 102));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/812075.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 750, 550));

        jLabel4.setText("Ganador");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Interfaz().setVisible(true);
                zeldaImg.setVisible(false);
                streetImg.setVisible(false);
                eliminar_trofeo_zelda();
                eliminar_trofeo_street();
                empate_desactivo();

            }
        });

        InteligenciaArtificial IA = new InteligenciaArtificial();
        Administrador admin = new Administrador();

        for (int a = 0; a < 20; a++) {
            Personaje personaje_zelda = Personaje.crear_personaje_zelda(Administrador.contId_zelda);
            Administrador.contId_zelda++;
            Administrador.encolarEnSuPrioridad(personaje_zelda);
        }

        for (int b = 0; b < 20; b++) {
            Personaje personaje_street = Personaje.crear_personaje_street(Administrador.contId_street);
            Administrador.contId_street++;
            Administrador.encolarEnSuPrioridad(personaje_street);

        }

        for (int rondas = 0; rondas < 100; rondas++) {
            if (Administrador.fin) {
                break;
            }
            
            int tiempo = (int) medidor_tiempo.getValue();
            System.out.println("TIEMPO: " + tiempo);
            try {
                System.out.println("TIEMPO SE ACTUALIZA");
                Thread.sleep(tiempo*1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Interfaz.cola1_zelda.setText("");
            Interfaz.cola1_street.setText("");

            Interfaz.cola2_zelda.setText("");
            Interfaz.cola2_street.setText("");

            Interfaz.cola3_zelda.setText("");
            Interfaz.cola3_street.setText("");

            Interfaz.cola4_zelda.setText("");
            Interfaz.cola4_street.setText("");

            colaZeldaNivel1.mostrar_cola_zelda();
            colaStreetFighterNivel1.mostrar_cola_street();

            colaZeldaNivel2.mostrar_cola_zelda();
            colaStreetFighterNivel2.mostrar_cola_street();

            colaZeldaNivel3.mostrar_cola_zelda();
            colaStreetFighterNivel3.mostrar_cola_street();

            colaZeldaNivel4.mostrar_cola_zelda();
            colaStreetFighterNivel4.mostrar_cola_street();
            
            Interfaz.cola_ganadores.setText("");
            ganadores.mostrar_cola_ganadores();
            
            cont_street_label.setText(String.valueOf(cont_street));
            cont_zelda_label.setText(String.valueOf(cont_zelda));
            
            

            System.out.println("----- RONDA" + rondas + "------");

            Personaje personaje_zelda = Administrador.obtenerPersonajeZelda();
            Personaje personaje_street = Administrador.obtenerPersonajeStreet();
            IA.procesarBatalla(personaje_zelda, personaje_street);
            eliminar_trofeo_zelda();
            eliminar_trofeo_street();

            Interfaz.cola1_zelda.setText("");
            Interfaz.cola1_street.setText("");

            Interfaz.cola2_zelda.setText("");
            Interfaz.cola2_street.setText("");

            Interfaz.cola3_zelda.setText("");
            Interfaz.cola3_street.setText("");

            Interfaz.cola4_zelda.setText("");
            Interfaz.cola4_street.setText("");

            colaZeldaNivel1.mostrar_cola_zelda();
            colaStreetFighterNivel1.mostrar_cola_street();

            colaZeldaNivel2.mostrar_cola_zelda();
            colaStreetFighterNivel2.mostrar_cola_street();

            colaZeldaNivel3.mostrar_cola_zelda();
            colaStreetFighterNivel3.mostrar_cola_street();

            colaZeldaNivel4.mostrar_cola_zelda();
            colaStreetFighterNivel4.mostrar_cola_street();
            
            Interfaz.cola_ganadores.setText("");
            ganadores.mostrar_cola_ganadores();
           
            
            //cont_street_label.setText(String.valueOf(cont_street));
            //cont_zelda_label.setText(String.valueOf(cont_zelda));
            
            empate_desactivo();

        }

    }

    public static JLabel getStreetImg() {
        return streetImg;
    }

    public static void setStreetImg(JLabel streetImg) {
        Interfaz.streetImg = streetImg;
    }

    public static JLabel getStreetName() {
        return streetName;
    }

    public static void setStreetName(JLabel streetName) {
        Interfaz.streetName = streetName;
    }

    public static JLabel getZeldaImg() {
        return zeldaImg;
    }

    public JLabel getTrofeo_street() {
        return trofeo_street;
    }

    public static JLabel getCola1_street() {
        return cola1_street;
    }

    public static JLabel getCola2_street() {
        return cola2_street;
    }

    public static JLabel getCola3_street() {
        return cola3_street;
    }

    public static JLabel getCola4_street() {
        return cola4_street;
    }

    public static JLabel getCola4_zelda() {
        return cola4_zelda;
    }

    public static void setCola1_street(JLabel cola1_street) {
        Interfaz.cola1_street = cola1_street;
    }

    public static void setCola2_street(JLabel cola2_street) {
        Interfaz.cola2_street = cola2_street;
    }

    public static void setCola3_street(JLabel cola3_street) {
        Interfaz.cola3_street = cola3_street;
    }

    public static void setCola4_street(JLabel cola4_street) {
        Interfaz.cola4_street = cola4_street;
    }

    public static void setCola4_zelda(JLabel cola4_zelda) {
        Interfaz.cola4_zelda = cola4_zelda;
    }

    public JLabel getTrofeo_zelda() {
        return trofeo_zelda;
    }

    public void setTrofeo_street(JLabel trofeo_street) {
        this.trofeo_street = trofeo_street;
    }

    public void setTrofeo_zelda(JLabel trofeo_zelda) {
        this.trofeo_zelda = trofeo_zelda;
    }

    public static void setZeldaImg(JLabel zeldaImg) {
        Interfaz.zeldaImg = zeldaImg;
    }

    public static void setEmpate(JLabel empate) {
        Interfaz.empate = empate;
    }

    public static JLabel getEmpate() {
        return empate;
    }

    public static JLabel getZeldaName() {
        return zeldaName;
    }

    public static void setZeldaName(JLabel zeldaName) {
        Interfaz.zeldaName = zeldaName;
    }

    public void setCola1_zelda(JLabel cola1_zelda) {
        this.cola1_zelda = cola1_zelda;
    }

    public void setCola2_zelda(JLabel cola2_zelda) {
        this.cola2_zelda = cola2_zelda;
    }

    public void setCola3_zelda(JLabel cola3_zelda) {
        this.cola3_zelda = cola3_zelda;
    }

    public JLabel getCola1_zelda() {
        return cola1_zelda;
    }

    public JLabel getCola2_zelda() {
        return cola2_zelda;
    }

    public JLabel getCola3_zelda() {
        return cola3_zelda;
    }

    public static JLabel getEstadoBatalla() {
        return estadoBatalla;
    }

    public static void setEstadoBatalla(JLabel estadoBatalla) {
        Interfaz.estadoBatalla = estadoBatalla;
    }

    public static void actualizarNombreZelda(String name) {
        if (zeldaName != null && zeldaImg != null) {
            zeldaName.setText(name);
            zeldaImg.setIcon(new ImageIcon("src//Imagenes//" + name + ".jpg"));
            zeldaImg.setVisible(true);

        }
    }

    public static void trofeo_zelda_activo() {
        trofeo_zelda.setVisible(true);
    }

    public static void trofeo_street_activo() {
        trofeo_street.setVisible(true);

    }

    public static void empate_activo() {
        empate.setIcon(new ImageIcon("src//Imagenes//" + "empate" + ".png"));
        empate.setVisible(true);
    }

    public static void no_combate() {
        empate.setIcon(new ImageIcon("src//Imagenes//" + "combate" + ".png"));
        empate.setVisible(true);
    }

    public static void empate_desactivo() {
        empate.setVisible(false);
    }

    public static void eliminar_trofeo_zelda() {
        trofeo_zelda.setVisible(false);
    }

    public static void eliminar_trofeo_street() {
        trofeo_street.setVisible(false);

    }

    public static void actualizarNombreStreet(String name) {
        if (streetName != null && streetImg != null) {
            streetName.setText(name);
            streetImg.setIcon(new ImageIcon("src//Imagenes//" + name + ".jpg"));
            streetImg.setVisible(true);
            cont_street_label.setText(String.valueOf(cont_street));
            cont_zelda_label.setText(String.valueOf(cont_zelda));
        }
    }

    public static void actualizarEstado(String estado) {
        if (estadoBatalla != null) {
            estadoBatalla.setText(estado);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Fondo;
    private javax.swing.JLabel TituloS;
    private javax.swing.JLabel TituloS1;
    private javax.swing.JLabel batallas_street;
    private javax.swing.JLabel batallas_zelda;
    public static javax.swing.JLabel cola1_street;
    public static javax.swing.JLabel cola1_zelda;
    public static javax.swing.JLabel cola2_street;
    public static javax.swing.JLabel cola2_zelda;
    public static javax.swing.JLabel cola3_street;
    public static javax.swing.JLabel cola3_zelda;
    public static javax.swing.JLabel cola4_street;
    public static javax.swing.JLabel cola4_zelda;
    public static javax.swing.JLabel cola_ganadores;
    public static javax.swing.JLabel cont_street_label;
    public static javax.swing.JLabel cont_zelda_label;
    public static javax.swing.JLabel empate;
    public static javax.swing.JLabel estadoBatalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JSpinner medidor_tiempo;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane2;
    private java.awt.ScrollPane scrollPane3;
    private java.awt.ScrollPane scrollPane4;
    private java.awt.ScrollPane scrollPane5;
    private java.awt.ScrollPane scrollPane6;
    private java.awt.ScrollPane scrollPane7;
    private java.awt.ScrollPane scrollPane8;
    private java.awt.ScrollPane scrollPane9;
    public static javax.swing.JLabel streetImg;
    public static javax.swing.JLabel streetName;
    public static javax.swing.JLabel trofeo_street;
    public static javax.swing.JLabel trofeo_zelda;
    private javax.swing.JLabel vs_imagen;
    public static javax.swing.JLabel zeldaImg;
    public static javax.swing.JLabel zeldaName;
    // End of variables declaration//GEN-END:variables
}
